name: Run tests

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    environment: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: "22.x"
        cache: 'npm'
    - run: touch .env
    - run: echo SESSION_SECRET=\"${{ secrets.SESSION_SECRET }}\" >> .env
    - run: echo MONGO_URL_TESTING=\"${{ secrets.MONGO_URL_TESTING }}\" >> .env
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
