name: Run tests

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    environment: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: "22.x"
        cache: 'npm'
    - shell: bash
      env:
        SESSION_SECRET: ${{ secrets.SESSION_SECRET_ENV }}
        MONGODB_URL_TESTING: ${{ secrets.MONGO_DB_ENV }}
      run: |
        npm ci
        npm run test -- --verbose --silent --coverage
